### ISSUE TITLE
PlexEmbySync crashes when a music video is played

### ISSUE THREAD

**Issue by carbonbaseunit** [AAndyProgram/PlexEmbySync#1]
Hi!
Thanks again for this wonderful little program.  It is perfect for my needs and I really appreciate you creating it.
It usually works flawlessly, but today I ran into a bit of a snafu.
I have music videos in a separate directory that Plex uses to incorporate them into my music library.  Whenever I play a music video from any player PlexEmbySync throws this error:  
`Playback monitoring error.  Value Cannot be null.  Parameter name: key`
I have to hit OK and then playback monitoring stops.
It's not that big a deal to me as I don't really watch music videos very often, but I wanted to let you know in case you wanted to fix it.
Thank You,
Shane

**Comment by AAndyProgram** [comment]
PlexEmbySync can only work with Movies and TV-Shows libraries. I didn't add the ability to work with other types of libraries. Just remove your music video library from PlexEmbySync and the error will go away.

**Comment by AAndyProgram** [comment]
Since I didn't receive your reply, I consider this issue resolved.
