### ISSUE TITLE
How can I sync two Plex Servers with Emby?

### ISSUE THREAD

**Issue by Neobond** [AAndyProgram/PlexEmbySync#10]
I have my Plex server on my NAS used for Direct Play, and I have a Plex Server on my Nvidia Shield that supports HW transcoding (the NAS does not) and is also accessible from outside my network on a non standard port.

The NAS Plex Server syncs from Emby using PlexEmbySync, but how do I also sync the second Plex Server on my network?

I am running PlexEmbySync app inside a Windows Server 2016 VM in my DS923+

Thanks in advance.

**Comment by AAndyProgram** [comment]
IDK
