### ISSUE TITLE
List of Emby users is incomplete

### ISSUE THREAD

**Issue by iamwoz** [AAndyProgram/PlexEmbySync#4]
Just setting up, PlexEmbySync reads my list of users but it is incomplete and is missing the user that I want to sync "Woz"
It finds 14 users - I have 16 users in Emby v4.7.10.0
This user is an Admin user.
Cheers!

**Comment by AAndyProgram** [comment]
As far as I remember, there you can add a user manually

**Comment by iamwoz** [comment]
Ah ok will try that thanks
