### ISSUE TITLE
sync currently playing between both servers

### ISSUE THREAD

**Issue by binarygeek119** [AAndyProgram/PlexEmbySync#6]
i like to use this program to use postarr to sync whats playing on emby but postarr is plex only i can use postarr to get posters from plex but i cant show whats playing on emby to plex

**Comment by AAndyProgram** [comment]
So what is your question?

**Comment by binarygeek119** [comment]
Well it doesn't sync. Is it supposed to sync

**Comment by AAndyProgram** [comment]
What version of Plex and Emby are you using?
These are mine:
PMS: 1.25.8.5663
Emby: 4.7.11.0

**Comment by binarygeek119** [comment]
Emby
4.8.0.29

Plex
1.32.1.6954

**Comment by AAndyProgram** [comment]
>Emby 4.8.0.29

This is a beta release. A couple of users told me that they had the same issue with beta versions. Sorry. I'm using the latest stable version of Emby and have no issues.

If the problem is in the Plex, unfortunately I can't help you. I see that your Plex is the latest version. Mine is not. This is because I use a personal agent for movies and TV. And while Plex insists on its ridiculous intention to force-remove all non-Plex user agents from Plex in future versions (and threats to do so have become much more intensive in the last year), I'm very caution about upgrading my Plex (first on WM, next on the server). I'm currently working on [SCrawler](https://github.com/AAndyProgram/SCrawler) and don't have time to test new Plex versions.

**Comment by binarygeek119** [comment]
ive down graded to the same as you and still its not doing it.

here my logs
[Log_003.txt](https://github.com/AAndyProgram/PlexEmbySync/files/11298368/Log_003.txt)
[UpdatingLog_20230421_132423.txt](https://github.com/AAndyProgram/PlexEmbySync/files/11298369/UpdatingLog_20230421_132423.txt)
[UpdatingLog_20230421_131719.txt](https://github.com/AAndyProgram/PlexEmbySync/files/11298370/UpdatingLog_20230421_131719.txt)
[UpdatingLog_20230421_130920.txt](https://github.com/AAndyProgram/PlexEmbySync/files/11298371/UpdatingLog_20230421_130920.txt)

**Comment by AAndyProgram** [comment]
I see that something has been updated.
1st
```
2023-04-21 12:51:52: [binarygeek119] Ed, Edd n Eddy Season 2 Episode 20 (00:00:00/00:11:23)
2023-04-21 13:06:12: [binarygeek119] Ed, Edd n Eddy Season 2 Episode 20 (00:00:00/00:11:23)
2023-04-21 13:09:20: Updating Plex data by Emby done
0 hours 10 minutes 12 seconds
```
2nd
```
2023-04-21 13:12:26: [binarygeek119] Ed, Edd n Eddy Season 2 Episode 20 (00:06:10/00:11:23)
2023-04-21 13:17:19: Updating Plex data by Emby done
0 hours 3 minutes 57 seconds
```
3rd
```
2023-04-21 13:18:24: [binarygeek119] Ed, Edd n Eddy Season 2 Episode 20 (00:06:43/00:11:23)
2023-04-21 13:24:23: Updating Plex data by Emby done
0 hours 3 minutes 43 seconds
```

As far as I can see, the first update was processed with some errors. But the other two were successfully completed. And `UpdatingLog_*.txt` confirms it.

Are you saying that nothing was updated at all?

**Comment by binarygeek119** [comment]
ive played with this some more.
i deleted the app and started over. 

Emby
4.7.11.0
and 
4.8.0.29 

Plex
1.32.1.6954

if i play something in plex is shows up in app.
if i play something in emby ether version nothing shows up.
im running unraid and im using docker for both emby and plex.
im switch back and forth between the beta and stable version of emby.

heres the log i see right now.

```
2023-04-25 03:49:33: API.Plex.Functions.GetUserItemsList
	One or more errors occurred.
2023-04-25 03:49:33: Message: One or more errors occurred.
	HelpLink: 
	StackTrace:    at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
	   at PlexEmbySync.API.Plex.Functions.GetUserItemsList(Library _Library, UserData _User, Boolean UsingTasks, CancellationToken Token)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: Index was outside the bounds of the array.
	HelpLink: 
	StackTrace:    at System.Collections.Generic.List`1.Add(T item)
	   at PlexEmbySync.API.Plex.Functions._Closure$__8-1._Lambda$__0()
	   at System.Threading.Tasks.Task.Execute()
2023-04-25 03:49:33: Updating Plex data by Emby done
	0 hours 5 minutes 38 seconds
```

**Comment by binarygeek119** [comment]
![image](https://user-images.githubusercontent.com/72405030/234228946-6aa4931d-0248-4adf-b65b-bea2855166f0.png)

![image](https://user-images.githubusercontent.com/72405030/234229404-29d4e768-72ee-4201-bdbe-181bbc8369ad.png)

**Comment by binarygeek119** [comment]
im now getting this

```
2023-04-26 01:13:16: API.Emby.EmbyItem.UpdateOffset
	[Response.GetResponse]:
	500 (InternalServerError)
	URL: [http://192.168.1.x:8096/emby/Users/b6202581deleted82c53b6388c2/Items/10003/UserData?Played=False&api_key=7d2021e3d02deleted8f20adad6eaac7]
	The remote server returned an error: (500) Internal Server Error.
2023-04-26 01:13:16: Message: [Response.GetResponse]:
	500 (InternalServerError)
	URL: [http://192.168.1.x:8096/emby/Users/b62025deleted8c782c53b6388c2/Items/10003/UserData?Played=False&api_key=7d202deleted2547d0bf8f20adad6eaac7]
	The remote server returned an error: (500) Internal Server Error.
	HelpLink: 
	StackTrace:    at PersonalUtilities.Functions.UniversalFunctions.ErrorsDescriber.Execute(ErrorsDescriber e, Exception ex, MMessage _Message, Object OptionalValueReturn)
	   at PersonalUtilities.Tools.WEB.Response.ReturnError(Exception& ex, ErrorsDescriber e, String URL)
	   at PersonalUtilities.Tools.WEB.Response.GetResponse(String URL, String PayLoad, ErrorsDescriber e)
	   at PlexEmbySync.API.Emby.EmbyItem.UpdateOffset(Boolean IgnoreSource)
	-----InnerException 1-----
	
	-----InnerException 2-----
	Message: The remote server returned an error: (500) Internal Server Error.
	HelpLink: 
	StackTrace:    at System.Net.HttpWebRequest.GetResponse()
	   at PersonalUtilities.Tools.WEB.Response.GetResponse(String URL, String PayLoad, ErrorsDescriber e)
```

**Comment by AAndyProgram** [comment]
In reply to a [comment](https://github.com/AAndyProgram/PlexEmbySync/issues/6#issuecomment-1521440239):
I think this is because you are running the same file on both servers at the same time.

In reply to a [comment](https://github.com/AAndyProgram/PlexEmbySync/issues/6#issuecomment-1521432858):
I don't know. Try deleting the settings folder (PlexEmbySync) and configure it again. Make sure you set up ALL the users you need, user tags (for playlists if you need to), LIBRARIES, tokens, and other required stuff.
