### ISSUE TITLE
Send to systray on Windows boot

### ISSUE THREAD

**Issue by Neobond** [AAndyProgram/PlexEmbySync#7]
Is there  a command to start this program quietly in Windows, so it goes directly to systray?

Thanks.

**Comment by AAndyProgram** [comment]
No. I think it's not so hard, when you run the program, click the close button to hide the program in the tray. 😊

**Comment by Neobond** [comment]
> No. I think it's not so hard, when you run the program, click the close button to hide the program in the tray. 😊

Oh okay, I will do exactly as you tell me.
