### ISSUE TITLE
Playlist Sync

### ISSUE THREAD

**Issue by ellisd4** [AAndyProgram/PlexEmbySync#8]
I am trying to sync music playlists from Plex to Emby.  I have added the "Shared Playlist" to the Plex summary field, but still get the "No one playlist have owner" error message.  Have I added the field incorrectly?  I followed the instructions [here](https://github.com/AAndyProgram/PlexEmbySync#playlists-settings).  The playlist tag field is empty on both users. 

PMS: 1.32.1.6983
Emby: 4.8.0.30 (beta)

![image](https://user-images.githubusercontent.com/109323886/234043182-c2c471d7-f3b4-4ba2-9f9e-f42a7695ee95.png)

```
2023-04-24 09:45:05: Updating Emby data by Plex done
	0 hours 2 minutes 49 seconds
2023-04-24 10:19:18: Playlists updating error
	No one playlist have owner
	Parameter name: Playlist owner
2023-04-24 10:19:18: Message: No one playlist have owner
	Parameter name: Playlist owner
	HelpLink: 
	StackTrace:    at PlexEmbySync.API.Plex.PlexPlaylists.Update()
	   at PlexEmbySync.BackWorker.StartPlaylistsUpdating(Nullable`1 _Server, Boolean Standalone, ErrorsDescriber e)
2023-04-24 10:23:42: Playlists updating error
	No one playlist have owner
	Parameter name: Playlist owner
2023-04-24 10:23:42: Message: No one playlist have owner
	Parameter name: Playlist owner
	HelpLink: 
	StackTrace:    at PlexEmbySync.API.Plex.PlexPlaylists.Update()
	   at PlexEmbySync.BackWorker.StartPlaylistsUpdating(Nullable`1 _Server, Boolean Standalone, ErrorsDescriber e)
```

**Comment by AAndyProgram** [comment]
https://github.com/AAndyProgram/PlexEmbySync#playlists-settings

>To work with updating playlists, you must set an Owner (playlist Tag field in Emby) for each playlist you have, and this Tag you must add to the [Plex and Emby user](https://github.com/AAndyProgram/PlexEmbySync#get-users)

I think you still need to configure playlist tags for users. It was a long time ago. I don't remember the code. But if I wrote that the tags must be configured, then it must be so. I have playlists with and without tags and all playlists are in sync.

**Comment by ellisd4** [comment]
I see.. would you mind sharing what that tag looks like? I have this: 
![image](https://user-images.githubusercontent.com/109323886/234057793-7e83ddc9-a375-428a-82c2-b98d497e4b2b.png)
Should I do something like "Owner: ellisd4"

**Comment by AAndyProgram** [comment]
I think you can use this tag if Emby accepts tags with spaces. I prefer to use tags without spaces. Of course you need to set up this tag in Emby as well.

**Comment by ellisd4** [comment]
> I think you can use this tag if Emby accepts tags with spaces. I prefer to use tags without spaces. Of course you need to set up this tag in Emby as well.

Thanks!  I used a no space tag and that didn't work, but I created a dummy playlist and created a tag on that playlist named "SharedPlaylist" and that allowed the sync to happen.  New issue though... Emby 4.8.0.21+ does not support xml playlists and only supports m3u playlists.

**Comment by AAndyProgram** [comment]
>and that allowed the sync to happen.

Good

>Emby 4.8.0.21+ does not support xml playlists and only supports m3u playlists.

I'll take a look at it when this release becomes stable.
