### ISSUE TITLE
Emby not updated

### ISSUE THREAD

**Issue by NPadrutt** [AAndyProgram/PlexEmbySync#9]
I try to sync from Plex to Emby. For the setup I followed the assistant. 
When I run the PlexEmbySync it is gathering data from Plex for my user and library and in the end reports that it updated like 7700 entries. But when I look into the Emby app itself no of the shows where actually marked as watched.

The Log only states:

```
2023-07-22 14:42:43: Updating Emby data by Plex done
	0 hours 5 minutes 3 seconds
```

Do you have any idea what I'm doing wrong?

Plex:  1.32.5.7328
Emby: 4.7.13.0

**Comment by AAndyProgram** [comment]
I don't know. Currently, after Emby release 1.25, there are problems with the bulk data update. I even disabled full library auto-update. Maybe the next Emby release will fix the problem. For now, I can only advice you to do the same (disable full library auto-update), wait at least a couple of hours, restart PES (PlexEmbySync), and when try again (manually). It works for me this way.

On the other hand, if PES told you that the 7700 updated but in fact nothing, IDK. 

Are you sure you've configured correctly? Check users bindings, libraries, tokens, etc.

My configuration:
Plex: 1.25.8.5663
Emby: 4.7.13.0

**Comment by NPadrutt** [comment]
Do you mean Plex Version 1.25? Since Emby 1.25 would be years ago, right?
From what I see is that it works to read things from Plex but not writing it to Emby. Since when I have the monitoring it shows stuff playing on plex but not on Emby. So it seems there is an authorization issue on Emby, but I don't really understand why since it can load the library and users and I created an API token for the sync.

**Comment by NPadrutt** [comment]
Also, I think I was wrong in terms of the message. It just stated that it's done updating Emby from plex, but nothing about the amount of entries. And it's very quick after the collection of data from plex to finish again, which would also point to an issue with the sync towards emby.

**Comment by AAndyProgram** [comment]
> Do you mean Plex Version 1.25? Since Emby 1.25 would be years ago, right?

Yeah, I guess a couple of years. Maybe three. Too busy working and developing my other project, [SCrawler](https://github.com/AAndyProgram/SCrawler).

I also use a personal agent for movies and TV. And while Plex insists on its ridiculous intent to forcibly remove all non-Plex user agents from Plex in future versions (and threats to do so have become much more intensive from year to year), I'm very cautious about upgrading my Plex (first on VM, then on the server).

So I don't touch anything around the media servers, while its works.

> So it seems there is an authorization issue on Emby, but I don't really understand why since it can load the library and users and I created an API token for the sync.

Again, everything works for me. I think you configured something wrong. Have you added a token from Emby to PES? I need to see your PES settings files. You can send them to me on Discord (andyprogram) or [email](mailto:andyprogram@proton.me) (andyprogram@proton.me).

**Comment by NPadrutt** [comment]
The cause here, was that my plex was configured with different Server Paths for the same library than my Emby Server.
